### ISSUE TITLE
Upgrade CNI to 1.9 on live (on k8s 1.20)

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform-user-guide#956]

**Comment by davidread** [comment]
Split this work off from #3282 for clarity?

**Comment by vijay-veeranki** [comment]
https://docs.google.com/document/d/1dNdDFXWhRcgtoMcZyZl0oNXz5MxU3slvZXmicouk3Fg/edit

https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1424/files

https://github.com/ministryofjustice/cloud-platform-terraform-vpc-cni

This is to adopt the resources into a release as guided in helm chart
https://github.com/aws/eks-charts/tree/master/stable/aws-vpc-cni#adopting-the-existing-aws-node-resources-in-an-eks-cluster

https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1424/commits/97c8979ecc2426b6d4bd296ac1b805f9bca99944

this is with using addon instead of using helm chart as above comment

**Comment by vijay-veeranki** [comment]
We decided to go with addon for cni.

**Comment by davidread** [comment]
Closing in favour of ticket in other repo: https://github.com/ministryofjustice/cloud-platform/issues/3420
